kind: pipeline
type: kubernetes
steps:
  - name: test
    image: node:alpine
    commands:
      - cd server
      - npm install
      - npm audit
  - name: docker
    image: plugins/kaniko
    environment:
      PLUGIN_USERNAME:
        from_secret: username
      PLUGIN_PASSWORD:
        from_secret: password
      PLUGIN_TAGS: server
      PLUGIN_REPO: munhunger/devban
      PLUGIN_DOCKERFILE: server/Dockerfile
    settings:
      context: server
  - name: deploy
    image: sinlead/drone-kubectl
    commands:
      - kubectl --namespace="devban" rollout restart deployment/node
---
kind: secret
name: username
get:
  path: docker
  name: username
---
kind: secret
name: password
get:
  path: docker
  name: password
